#!/bin/bash

export B2ACCESS_CONSUMER_KEY='{{ b2access_consumer_key }}'
export B2ACCESS_SECRET_KEY='{{ b2access_secret_key }}'
export B2SHARE_SECRET_KEY='SECRET-KEY'

export B2SHARE_JSONSCHEMAS_HOST='{{ b2share_jsonschemas_host }}:{{ b2share_jsonschemas_port }}'

export B2SHARE_POSTGRESQL_DBNAME=dbname
export B2SHARE_POSTGRESQL_USER=user
export B2SHARE_POSTGRESQL_PASSWORD=password

export B2SHARE_DATADIR='/home/vagrant/b2share-data' 
export B2SHARE_UI_PATH=$HOME/b2share/webui/app


export USE_STAGING_B2ACCESS=1                 
## Configuration for support services
export B2SHARE_RABBITMQ_USER=user
export B2SHARE_RABBITMQ_PASS=pass

export B2SHARE_POSTGRESQL_DBNAME=dbname
export B2SHARE_POSTGRESQL_USER=user
export B2SHARE_POSTGRESQL_PASSWORD=password

export B2SHARE_PREFERRED_URL_SCHEME=http
export B2SHARE_SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://${B2SHARE_POSTGRESQL_USER}:${B2SHARE_POSTGRESQL_PASSWORD}@localhost:5432/${B2SHARE_POSTGRESQL_DBNAME}"
export B2SHARE_CACHE_REDIS_HOST='redis'
export B2SHARE_CACHE_REDIS_URL='redis://localhost:6379/0'
export B2SHARE_ACCOUNTS_SESSION_REDIS_URL='redis://localhost:6379/1'
export B2SHARE_BROKER_URL="amqp://${B2SHARE_RABBITMQ_USER}:${B2SHARE_RABBITMQ_PASS}@localhost:5672/"
export B2SHARE_CELERY_BROKER_URL="amqp://${B2SHARE_RABBITMQ_USER}:${B2SHARE_RABBITMQ_PASS}@localhost:5672/"
export B2SHARE_CELERY_RESULT_BACKEND='redis://localhost:6379/2'
export B2SHARE_SEARCH_ELASTIC_HOSTS='localhost'

export BRIDGE_URL=http:'{{ bridge_ip_address }}:{{ bridge_port }}'/api/v1
export BRIDGE_APIKEY='{{ bridge_apikey }}'
export BRIDGE_DAR_USERNAME='{{ bridge_dar_username }}'
export BRIDGE_DAR_PASSWORD='{{ bridge_dar_password }}'

export LC_ALL=en_US.utf8
export LANG=en_US.utf8
